Adds module factory interface
Dhii/module-interface pull request #11
Opened 2018-03-14 15:31 UTC by mecha

Resolves #10

2018-03-14 15:33 UTC, XedinUnknown requested changes

2018-03-14 15:33 UTC, XedinUnknown commented on composer.json
> +        "dhii/factory-interface": "0.1-alpha2"
Can't we allow `0.1-alpha1` as well??

2018-03-14 15:35 UTC, mecha commented on composer.json
> +        "dhii/factory-interface": "0.1-alpha2"
Good question. Checking ...

2018-03-14 15:38 UTC, mecha commented on composer.json
> +        "dhii/factory-interface": "0.1-alpha2"
We can, yes.

2018-04-16 08:19 UTC, XedinUnknown approved these changes

2018-04-16 11:45 UTC, merged